name: Update Recent Activity

on:
  workflow_dispatch:  # Para ejecutar manualmente
  schedule:
    - cron: '0 */6 * * *'  # Cada 6 horas

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      # Paso 1: Descargar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # Paso 2: Usar la acción de jamesgeorge007
      - name: Update README with activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MAX_LINES: 8  # Número de actividades a mostrar
